version: '3.8'

services:
  web:
    image: oven/bun:latest
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: "bun install && bun dev"
    environment:
      - NODE_ENV=development
