import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "~/lib/utils";

import "./globals.css";
import Link from "next/link";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="flex">
          <div className="relative">
            <div className="h-dvh p-10 rounded-r-lg w-fit sticky top-0 bg-secondary-foreground text-secondary space-y-10">
              <div>
                <h1>IXC O.S. Killer</h1>
              </div>
              <nav className="flex flex-col">
                <Link href="#">Fechar O.S.</Link>
                <Link href="#">Fechar atendimentos</Link>
                <Link href="#">Depuração</Link>
              </nav>
            </div>
          </div>
          <div className="flex-1 p-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
